"""What counts as pairing HISTORY (Kerry 2026-09-08).

"For the pairings, you're not counting pairings generated by the app that
were never used right? At the moment final GG pairings is what rules."

We were. Saving a sheet writes source='app' rows immediately, so a
grouping the app merely PROPOSED scored the same as one that teed off —
and a sheet saved for a future event made the generator treat pairs it
had just proposed as repeats, so hitting Generate twice fought its own
first answer.

Two rules, pinned here:
  1. Golf Genius is the ONLY source. Kerry 2026-09-08: "GG is only
     source at the moment. Erase any tracker history rows. That will
     change once we get rid of GG."
  2. Nothing counts until it has been played — for every source. Kerry:
     an app row is "a plan until the round is played", "And GG could
     also change until tee off." So the cutoff is event_date < today.

Run: python3 test_pairing_history_rule.py
"""

import os
import sys
import tempfile
from datetime import timedelta

os.environ.setdefault("DATABASE_PATH", ":memory:")

from email_parser import database as db  # noqa: E402
from email_parser.timezone_utils import today_central  # noqa: E402

FAILURES = []


def check(label, cond, detail=""):
    print(("  PASS  " if cond else "  FAIL  ") + label
          + ("" if cond else "  " + str(detail)))
    if not cond:
        FAILURES.append(label)


def add(conn, a, b, event_id, date, source):
    conn.execute(
        "INSERT INTO pairing_history (player_a, player_b, event_id, "
        "event_date, rode, source) VALUES (?,?,?,?,0,?)",
        (min(a, b), max(a, b), event_id, date, source))


def main():
    tmp = tempfile.NamedTemporaryFile(suffix=".db", delete=False)
    tmp.close()
    p = tmp.name
    today = today_central()
    past = (today - timedelta(days=7)).strftime("%Y-%m-%d")
    past2 = (today - timedelta(days=14)).strftime("%Y-%m-%d")
    future = (today + timedelta(days=7)).strftime("%Y-%m-%d")
    yr = today.year

    with db._connect(p) as conn:
        db._ensure_pairing_tables(conn)
        # Event 1, played: GG has it AND the app proposed something else.
        # GG rules — the app pair must not count.
        add(conn, "Ann Real", "Bob Real", 1, past, "gg_teesheet")
        add(conn, "Ann Real", "Cal Proposed", 1, past, "app")
        # Event 2, played, GG never ingested: the app rows are the only
        # record of what happened, so they count.
        add(conn, "Dee Only", "Eve Only", 2, past2, "app")
        # Event 3, NOT YET PLAYED: saved in the app. A plan, not history.
        add(conn, "Fay Future", "Gus Future", 3, future, "app")
        # Event 4, not yet played, and somehow GG-sourced: still future.
        add(conn, "Hal Future", "Ivy Future", 4, future, "gg_teesheet")
        conn.commit()

    counts = db.get_pairing_history_counts(year=yr, db_path=p)

    def n(a, b):
        a, b = db._pair_key_name(a), db._pair_key_name(b)
        return counts.get((min(a, b), max(a, b)), 0)

    check("a GG pair on a played event counts",
          n("Ann Real", "Bob Real") == 1, counts)
    check("an APP pair is ignored when GG has that event",
          n("Ann Real", "Cal Proposed") == 0, counts)
    check("an APP pair is ignored even when GG never ingested the event "
          "— GG is the only source",
          n("Dee Only", "Eve Only") == 0, counts)
    check("a pairing saved for a FUTURE event never counts",
          n("Fay Future", "Gus Future") == 0, counts)
    check("... not even a GG-sourced future one",
          n("Hal Future", "Ivy Future") == 0, counts)
    check("nothing else leaked in", len(counts) == 1, counts)

    # The regression that started it: save a sheet, regenerate, and the
    # generator must not treat its own proposal as a prior play.
    with db._connect(p) as conn:
        add(conn, "Jan Same", "Kim Same", 3, future, "app")
        conn.commit()
    counts2 = db.get_pairing_history_counts(year=yr, db_path=p)
    check("re-generating an unplayed event does not fight its own save",
          counts2 == counts, counts2)

    # TODAY is the case that actually bit: Kerry saved tonight's sheet
    # and the generator scored it against itself hours before anyone
    # teed off. An app row is a plan until the round is played.
    todays = today.strftime("%Y-%m-%d")
    with db._connect(p) as conn:
        add(conn, "Lee Tonight", "Moe Tonight", 5, todays, "app")
        add(conn, "Ned Posted", "Oli Posted", 6, todays, "gg_teesheet")
        conn.commit()
    c3 = db.get_pairing_history_counts(year=yr, db_path=p)

    def n3(a, b):
        a, b = db._pair_key_name(a), db._pair_key_name(b)
        return c3.get((min(a, b), max(a, b)), 0)

    check("an APP sheet saved for TODAY does not count — it is still "
          "a plan at 9 in the morning",
          n3("Lee Tonight", "Moe Tonight") == 0, c3)
    check("nor does a GG row for TODAY — GG can change until tee off",
          n3("Ned Posted", "Oli Posted") == 0, c3)

    # And the belt: the event being generated for is never its own
    # history, whatever the dates say.
    with db._connect(p) as conn:
        add(conn, "Pam Self", "Quin Self", 7, past, "gg_teesheet")
        conn.commit()
    c4 = db.get_pairing_history_counts(year=yr, db_path=p)
    c5 = db.get_pairing_history_counts(year=yr, db_path=p,
                                       exclude_event_id=7)

    def has(counts_, a, b):
        a, b = db._pair_key_name(a), db._pair_key_name(b)
        return counts_.get((min(a, b), max(a, b)), 0)

    check("a played GG pair counts normally",
          has(c4, "Pam Self", "Quin Self") == 1, c4)
    check("... and is excluded when generating for THAT event",
          has(c5, "Pam Self", "Quin Self") == 0, c5)
    check("excluding one event leaves the rest alone",
          has(c5, "Ann Real", "Bob Real") == 1, c5)

    # Saving a sheet must not write history while GG is the record, and
    # the saved sheet itself must survive so the table can be rebuilt.
    with db._connect(p) as conn:
        conn.execute("CREATE TABLE IF NOT EXISTS app_settings ("
                     "key TEXT PRIMARY KEY, value TEXT, updated_at TEXT)")
        conn.execute("CREATE TABLE IF NOT EXISTS events ("
                     "id INTEGER PRIMARY KEY, item_name TEXT, "
                     "event_date TEXT)")
        conn.execute("CREATE TABLE IF NOT EXISTS customers ("
                     "customer_id INTEGER PRIMARY KEY, first_name TEXT, "
                     "last_name TEXT)")
        conn.execute("INSERT OR REPLACE INTO events VALUES (99, 'Test', ?)",
                     (past,))
        conn.commit()
    sheet = {"9": [{"group_num": 1, "slot_label": "HOLE 1A", "players": [
        {"name": "Rae Saved", "cart_pos": 1, "tee_choice": "<50",
         "handicap_index": 5.0},
        {"name": "Sam Saved", "cart_pos": 2, "tee_choice": "<50",
         "handicap_index": 6.0}]}]}
    db.save_event_pairings(99, sheet, db_path=p)
    with db._connect(p) as conn:
        n_hist = conn.execute(
            "SELECT COUNT(*) FROM pairing_history WHERE event_id = 99"
        ).fetchone()[0]
        n_sheet = conn.execute(
            "SELECT COUNT(*) FROM event_pairings WHERE event_id = 99"
        ).fetchone()[0]
    check("saving a sheet writes NO history while GG is the record",
          n_hist == 0, n_hist)
    check("but the saved sheet itself is kept, so history can be "
          "rebuilt when the app becomes the record",
          n_sheet == 2, n_sheet)

    # And the dial is the whole change for the post-GG world.
    db.set_app_setting("pairing_history_app_writes", "1", db_path=p)
    db.save_event_pairings(99, sheet, db_path=p)
    with db._connect(p) as conn:
        n_hist2 = conn.execute(
            "SELECT COUNT(*) FROM pairing_history WHERE event_id = 99"
        ).fetchone()[0]
    check("flipping pairing_history_app_writes turns writing back on",
          n_hist2 == 1, n_hist2)

    # The purge Kerry asked for: app rows go, GG rows stay.
    db.set_app_setting("pairing_history_app_writes", "0", db_path=p)
    dry = db.purge_app_pairing_history(dry_run=True, db_path=p)
    check("the purge dry-runs before it deletes", dry["dry_run"] is True)
    check("the dry run counts the app rows it would remove",
          dry["rows"] > 0, dry)
    done = db.purge_app_pairing_history(dry_run=False, db_path=p)
    with db._connect(p) as conn:
        left = {r[0]: r[1] for r in conn.execute(
            "SELECT COALESCE(source,'app'), COUNT(*) FROM pairing_history "
            "GROUP BY COALESCE(source,'app')")}
    check("every app row is gone after the purge",
          left.get("app", 0) == 0, left)
    check("the Golf Genius rows are untouched",
          left.get("gg_teesheet", 0) > 0, left)
    check("and the saved sheets survive the purge",
          done["saved_sheets_kept"] >= 1, done)

    print()
    if FAILURES:
        print(f"{len(FAILURES)} FAILED: " + ", ".join(FAILURES))
        sys.exit(1)
    print("All checks passed.")


if __name__ == "__main__":
    main()
